In [3]:
import numpy as nm
import pandas as pd

In [55]:
# importing the dataset
dataset=pd.read_csv('user_data.csv')

In [9]:
dataset

Gender   Age    EstimatedSalary  purchased
0     Male     19             19000          0
1     Male     35             20000          0
2   Female     26             43000          0
3   Female     27             57000          0
4     Male     19             76000          0
5     Male     27             58000          0
6   Female     27             84000          0
7   Female     32            150000          1
8     Male     25             33000          0
9   Female     35             65000          0
10  Female     26             80000          0
11  Female     26             52000          0
12    Male     20             86000          0
13    Male     32             18000          0
14    Male     18             82000          0
15    Male     29             80000          0
16    Male     47             25000          1
17   Male      45             26000          1
18    Male     46             28000          1
19  Female     48             29000          1

In [25]:
x=dataset.iloc[:,[1,2]].values

In [29]:
y=dataset.iloc[:,3].values

In [31]:
from sklearn.model_selection import train_test_split

In [56]:
#splitting the data into training and test set
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)

In [57]:
# feature scaling
from sklearn. preprocessing import StandardScaler

In [46]:
sc=StandardScaler()

In [47]:
x_train=sc.fit_transform(x_train)

In [48]:
x_test=sc.transform(x_test)

In [58]:
#Fitting naive bayes to training set
from sklearn.naive_bayes import GaussianNB
classifier=GaussianNB()
classifier.fit(x_train,y_train)

GaussianNB()

In [59]:
#predicting the test result
y_pred=classifier.predict(x_test)

In [51]:
from sklearn.metrics import confusion_matrix

In [52]:
confusion_matrix(y_test,y_pred)

array([[3, 0],
       [0, 2]], dtype=int64)

In [53]:
y_pred

array([1, 0, 1, 0, 0], dtype=int64)

In [54]:
y_test

array([1, 0, 1, 0, 0], dtype=int64)